// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.scaleway.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetLbIpArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetLbIpArgs Empty = new GetLbIpArgs();

    /**
     * The IP address.
     * Only one of `ip_address` and `ip_id` should be specified.
     * 
     */
    @Import(name="ipAddress")
    private @Nullable Output<String> ipAddress;

    /**
     * @return The IP address.
     * Only one of `ip_address` and `ip_id` should be specified.
     * 
     */
    public Optional<Output<String>> ipAddress() {
        return Optional.ofNullable(this.ipAddress);
    }

    /**
     * The IP ID.
     * Only one of `ip_address` and `ip_id` should be specified.
     * 
     */
    @Import(name="ipId")
    private @Nullable Output<String> ipId;

    /**
     * @return The IP ID.
     * Only one of `ip_address` and `ip_id` should be specified.
     * 
     */
    public Optional<Output<String>> ipId() {
        return Optional.ofNullable(this.ipId);
    }

    private GetLbIpArgs() {}

    private GetLbIpArgs(GetLbIpArgs $) {
        this.ipAddress = $.ipAddress;
        this.ipId = $.ipId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetLbIpArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetLbIpArgs $;

        public Builder() {
            $ = new GetLbIpArgs();
        }

        public Builder(GetLbIpArgs defaults) {
            $ = new GetLbIpArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param ipAddress The IP address.
         * Only one of `ip_address` and `ip_id` should be specified.
         * 
         * @return builder
         * 
         */
        public Builder ipAddress(@Nullable Output<String> ipAddress) {
            $.ipAddress = ipAddress;
            return this;
        }

        /**
         * @param ipAddress The IP address.
         * Only one of `ip_address` and `ip_id` should be specified.
         * 
         * @return builder
         * 
         */
        public Builder ipAddress(String ipAddress) {
            return ipAddress(Output.of(ipAddress));
        }

        /**
         * @param ipId The IP ID.
         * Only one of `ip_address` and `ip_id` should be specified.
         * 
         * @return builder
         * 
         */
        public Builder ipId(@Nullable Output<String> ipId) {
            $.ipId = ipId;
            return this;
        }

        /**
         * @param ipId The IP ID.
         * Only one of `ip_address` and `ip_id` should be specified.
         * 
         * @return builder
         * 
         */
        public Builder ipId(String ipId) {
            return ipId(Output.of(ipId));
        }

        public GetLbIpArgs build() {
            return $;
        }
    }

}
