// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.scaleway.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetRdbDatabasePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRdbDatabasePlainArgs Empty = new GetRdbDatabasePlainArgs();

    /**
     * The RDB instance ID.
     * 
     */
    @Import(name="instanceId", required=true)
    private String instanceId;

    /**
     * @return The RDB instance ID.
     * 
     */
    public String instanceId() {
        return this.instanceId;
    }

    /**
     * The name of the RDB instance.
     * 
     */
    @Import(name="name", required=true)
    private String name;

    /**
     * @return The name of the RDB instance.
     * 
     */
    public String name() {
        return this.name;
    }

    @Import(name="region")
    private @Nullable String region;

    public Optional<String> region() {
        return Optional.ofNullable(this.region);
    }

    private GetRdbDatabasePlainArgs() {}

    private GetRdbDatabasePlainArgs(GetRdbDatabasePlainArgs $) {
        this.instanceId = $.instanceId;
        this.name = $.name;
        this.region = $.region;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRdbDatabasePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRdbDatabasePlainArgs $;

        public Builder() {
            $ = new GetRdbDatabasePlainArgs();
        }

        public Builder(GetRdbDatabasePlainArgs defaults) {
            $ = new GetRdbDatabasePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param instanceId The RDB instance ID.
         * 
         * @return builder
         * 
         */
        public Builder instanceId(String instanceId) {
            $.instanceId = instanceId;
            return this;
        }

        /**
         * @param name The name of the RDB instance.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public Builder region(@Nullable String region) {
            $.region = region;
            return this;
        }

        public GetRdbDatabasePlainArgs build() {
            $.instanceId = Objects.requireNonNull($.instanceId, "expected parameter 'instanceId' to be non-null");
            $.name = Objects.requireNonNull($.name, "expected parameter 'name' to be non-null");
            return $;
        }
    }

}
