// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.scaleway.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetVpcPublicGatewayPatRulePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetVpcPublicGatewayPatRulePlainArgs Empty = new GetVpcPublicGatewayPatRulePlainArgs();

    /**
     * The ID of the PAT rule to retrieve
     * 
     */
    @Import(name="patRuleId", required=true)
    private String patRuleId;

    /**
     * @return The ID of the PAT rule to retrieve
     * 
     */
    public String patRuleId() {
        return this.patRuleId;
    }

    /**
     * `zone`) The zone in which
     * the image exists.
     * 
     */
    @Import(name="zone")
    private @Nullable String zone;

    /**
     * @return `zone`) The zone in which
     * the image exists.
     * 
     */
    public Optional<String> zone() {
        return Optional.ofNullable(this.zone);
    }

    private GetVpcPublicGatewayPatRulePlainArgs() {}

    private GetVpcPublicGatewayPatRulePlainArgs(GetVpcPublicGatewayPatRulePlainArgs $) {
        this.patRuleId = $.patRuleId;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetVpcPublicGatewayPatRulePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetVpcPublicGatewayPatRulePlainArgs $;

        public Builder() {
            $ = new GetVpcPublicGatewayPatRulePlainArgs();
        }

        public Builder(GetVpcPublicGatewayPatRulePlainArgs defaults) {
            $ = new GetVpcPublicGatewayPatRulePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param patRuleId The ID of the PAT rule to retrieve
         * 
         * @return builder
         * 
         */
        public Builder patRuleId(String patRuleId) {
            $.patRuleId = patRuleId;
            return this;
        }

        /**
         * @param zone `zone`) The zone in which
         * the image exists.
         * 
         * @return builder
         * 
         */
        public Builder zone(@Nullable String zone) {
            $.zone = zone;
            return this;
        }

        public GetVpcPublicGatewayPatRulePlainArgs build() {
            $.patRuleId = Objects.requireNonNull($.patRuleId, "expected parameter 'patRuleId' to be non-null");
            return $;
        }
    }

}
