// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.scaleway.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RdbAclAclRuleArgs extends com.pulumi.resources.ResourceArgs {

    public static final RdbAclAclRuleArgs Empty = new RdbAclAclRuleArgs();

    /**
     * A text describing this rule. Default description: `IP allowed`
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return A text describing this rule. Default description: `IP allowed`
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The ip range to whitelist in [CIDR notation](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#CIDR_notation)
     * 
     */
    @Import(name="ip", required=true)
    private Output<String> ip;

    /**
     * @return The ip range to whitelist in [CIDR notation](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#CIDR_notation)
     * 
     */
    public Output<String> ip() {
        return this.ip;
    }

    private RdbAclAclRuleArgs() {}

    private RdbAclAclRuleArgs(RdbAclAclRuleArgs $) {
        this.description = $.description;
        this.ip = $.ip;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RdbAclAclRuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RdbAclAclRuleArgs $;

        public Builder() {
            $ = new RdbAclAclRuleArgs();
        }

        public Builder(RdbAclAclRuleArgs defaults) {
            $ = new RdbAclAclRuleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description A text describing this rule. Default description: `IP allowed`
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description A text describing this rule. Default description: `IP allowed`
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param ip The ip range to whitelist in [CIDR notation](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#CIDR_notation)
         * 
         * @return builder
         * 
         */
        public Builder ip(Output<String> ip) {
            $.ip = ip;
            return this;
        }

        /**
         * @param ip The ip range to whitelist in [CIDR notation](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#CIDR_notation)
         * 
         * @return builder
         * 
         */
        public Builder ip(String ip) {
            return ip(Output.of(ip));
        }

        public RdbAclAclRuleArgs build() {
            $.ip = Objects.requireNonNull($.ip, "expected parameter 'ip' to be non-null");
            return $;
        }
    }

}
