// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Scaleway
{
    [ScalewayResourceType("scaleway:index/documentDBPrivateNetworkEndpoint:DocumentDBPrivateNetworkEndpoint")]
    public partial class DocumentDBPrivateNetworkEndpoint : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The hostname of your endpoint
        /// </summary>
        [Output("hostname")]
        public Output<string> Hostname { get; private set; } = null!;

        /// <summary>
        /// Instance on which the endpoint is attached
        /// </summary>
        [Output("instanceId")]
        public Output<string> InstanceId { get; private set; } = null!;

        /// <summary>
        /// The IP of your private network service
        /// </summary>
        [Output("ip")]
        public Output<string> Ip { get; private set; } = null!;

        /// <summary>
        /// The IP with the given mask within the private subnet
        /// </summary>
        [Output("ipNet")]
        public Output<string> IpNet { get; private set; } = null!;

        /// <summary>
        /// The name of your private service
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The port of your private service
        /// </summary>
        [Output("port")]
        public Output<int> Port { get; private set; } = null!;

        /// <summary>
        /// The private network ID
        /// </summary>
        [Output("privateNetworkId")]
        public Output<string> PrivateNetworkId { get; private set; } = null!;

        /// <summary>
        /// The region you want to attach the resource to
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// The zone you want to attach the resource to
        /// </summary>
        [Output("zone")]
        public Output<string> Zone { get; private set; } = null!;


        /// <summary>
        /// Create a DocumentDBPrivateNetworkEndpoint resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DocumentDBPrivateNetworkEndpoint(string name, DocumentDBPrivateNetworkEndpointArgs args, CustomResourceOptions? options = null)
            : base("scaleway:index/documentDBPrivateNetworkEndpoint:DocumentDBPrivateNetworkEndpoint", name, args ?? new DocumentDBPrivateNetworkEndpointArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DocumentDBPrivateNetworkEndpoint(string name, Input<string> id, DocumentDBPrivateNetworkEndpointState? state = null, CustomResourceOptions? options = null)
            : base("scaleway:index/documentDBPrivateNetworkEndpoint:DocumentDBPrivateNetworkEndpoint", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/dirien/pulumi-scaleway",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DocumentDBPrivateNetworkEndpoint resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DocumentDBPrivateNetworkEndpoint Get(string name, Input<string> id, DocumentDBPrivateNetworkEndpointState? state = null, CustomResourceOptions? options = null)
        {
            return new DocumentDBPrivateNetworkEndpoint(name, id, state, options);
        }
    }

    public sealed class DocumentDBPrivateNetworkEndpointArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Instance on which the endpoint is attached
        /// </summary>
        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        /// <summary>
        /// The IP with the given mask within the private subnet
        /// </summary>
        [Input("ipNet")]
        public Input<string>? IpNet { get; set; }

        /// <summary>
        /// The port of your private service
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// The private network ID
        /// </summary>
        [Input("privateNetworkId", required: true)]
        public Input<string> PrivateNetworkId { get; set; } = null!;

        /// <summary>
        /// The region you want to attach the resource to
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// The zone you want to attach the resource to
        /// </summary>
        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public DocumentDBPrivateNetworkEndpointArgs()
        {
        }
        public static new DocumentDBPrivateNetworkEndpointArgs Empty => new DocumentDBPrivateNetworkEndpointArgs();
    }

    public sealed class DocumentDBPrivateNetworkEndpointState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The hostname of your endpoint
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        /// <summary>
        /// Instance on which the endpoint is attached
        /// </summary>
        [Input("instanceId")]
        public Input<string>? InstanceId { get; set; }

        /// <summary>
        /// The IP of your private network service
        /// </summary>
        [Input("ip")]
        public Input<string>? Ip { get; set; }

        /// <summary>
        /// The IP with the given mask within the private subnet
        /// </summary>
        [Input("ipNet")]
        public Input<string>? IpNet { get; set; }

        /// <summary>
        /// The name of your private service
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The port of your private service
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// The private network ID
        /// </summary>
        [Input("privateNetworkId")]
        public Input<string>? PrivateNetworkId { get; set; }

        /// <summary>
        /// The region you want to attach the resource to
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// The zone you want to attach the resource to
        /// </summary>
        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public DocumentDBPrivateNetworkEndpointState()
        {
        }
        public static new DocumentDBPrivateNetworkEndpointState Empty => new DocumentDBPrivateNetworkEndpointState();
    }
}
