// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Scaleway
{
    public static class GetVpcPublicGatewayPatRule
    {
        /// <summary>
        /// Gets information about a public gateway PAT rule. For further information please check the
        /// API [documentation](https://developers.scaleway.com/en/products/vpc-gw/api/v1/#get-8faeea)
        /// </summary>
        public static Task<GetVpcPublicGatewayPatRuleResult> InvokeAsync(GetVpcPublicGatewayPatRuleArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetVpcPublicGatewayPatRuleResult>("scaleway:index/getVpcPublicGatewayPatRule:getVpcPublicGatewayPatRule", args ?? new GetVpcPublicGatewayPatRuleArgs(), options.WithDefaults());

        /// <summary>
        /// Gets information about a public gateway PAT rule. For further information please check the
        /// API [documentation](https://developers.scaleway.com/en/products/vpc-gw/api/v1/#get-8faeea)
        /// </summary>
        public static Output<GetVpcPublicGatewayPatRuleResult> Invoke(GetVpcPublicGatewayPatRuleInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetVpcPublicGatewayPatRuleResult>("scaleway:index/getVpcPublicGatewayPatRule:getVpcPublicGatewayPatRule", args ?? new GetVpcPublicGatewayPatRuleInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetVpcPublicGatewayPatRuleArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the PAT rule to retrieve
        /// </summary>
        [Input("patRuleId", required: true)]
        public string PatRuleId { get; set; } = null!;

        /// <summary>
        /// `zone`) The zone in which
        /// the image exists.
        /// </summary>
        [Input("zone")]
        public string? Zone { get; set; }

        public GetVpcPublicGatewayPatRuleArgs()
        {
        }
        public static new GetVpcPublicGatewayPatRuleArgs Empty => new GetVpcPublicGatewayPatRuleArgs();
    }

    public sealed class GetVpcPublicGatewayPatRuleInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the PAT rule to retrieve
        /// </summary>
        [Input("patRuleId", required: true)]
        public Input<string> PatRuleId { get; set; } = null!;

        /// <summary>
        /// `zone`) The zone in which
        /// the image exists.
        /// </summary>
        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public GetVpcPublicGatewayPatRuleInvokeArgs()
        {
        }
        public static new GetVpcPublicGatewayPatRuleInvokeArgs Empty => new GetVpcPublicGatewayPatRuleInvokeArgs();
    }


    [OutputType]
    public sealed class GetVpcPublicGatewayPatRuleResult
    {
        public readonly string CreatedAt;
        /// <summary>
        /// The ID of the public gateway.
        /// </summary>
        public readonly string GatewayId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string OrganizationId;
        public readonly string PatRuleId;
        /// <summary>
        /// The Private IP to forward data to (IP address).
        /// </summary>
        public readonly string PrivateIp;
        /// <summary>
        /// The Private port to translate to.
        /// </summary>
        public readonly int PrivatePort;
        /// <summary>
        /// The Protocol the rule should apply to. Possible values are both, tcp and udp.
        /// </summary>
        public readonly string Protocol;
        /// <summary>
        /// The Public port to listen on.
        /// </summary>
        public readonly int PublicPort;
        public readonly string UpdatedAt;
        public readonly string? Zone;

        [OutputConstructor]
        private GetVpcPublicGatewayPatRuleResult(
            string createdAt,

            string gatewayId,

            string id,

            string organizationId,

            string patRuleId,

            string privateIp,

            int privatePort,

            string protocol,

            int publicPort,

            string updatedAt,

            string? zone)
        {
            CreatedAt = createdAt;
            GatewayId = gatewayId;
            Id = id;
            OrganizationId = organizationId;
            PatRuleId = patRuleId;
            PrivateIp = privateIp;
            PrivatePort = privatePort;
            Protocol = protocol;
            PublicPort = publicPort;
            UpdatedAt = updatedAt;
            Zone = zone;
        }
    }
}
