// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.scaleway.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetK8sClusterKubeconfig {
    /**
     * @return The CA certificate of the Kubernetes API server.
     * 
     */
    private String clusterCaCertificate;
    /**
     * @return The raw kubeconfig file.
     * 
     */
    private String configFile;
    /**
     * @return The URL of the Kubernetes API server.
     * 
     */
    private String host;
    /**
     * @return The token to connect to the Kubernetes API server.
     * 
     */
    private String token;

    private GetK8sClusterKubeconfig() {}
    /**
     * @return The CA certificate of the Kubernetes API server.
     * 
     */
    public String clusterCaCertificate() {
        return this.clusterCaCertificate;
    }
    /**
     * @return The raw kubeconfig file.
     * 
     */
    public String configFile() {
        return this.configFile;
    }
    /**
     * @return The URL of the Kubernetes API server.
     * 
     */
    public String host() {
        return this.host;
    }
    /**
     * @return The token to connect to the Kubernetes API server.
     * 
     */
    public String token() {
        return this.token;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetK8sClusterKubeconfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String clusterCaCertificate;
        private String configFile;
        private String host;
        private String token;
        public Builder() {}
        public Builder(GetK8sClusterKubeconfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.clusterCaCertificate = defaults.clusterCaCertificate;
    	      this.configFile = defaults.configFile;
    	      this.host = defaults.host;
    	      this.token = defaults.token;
        }

        @CustomType.Setter
        public Builder clusterCaCertificate(String clusterCaCertificate) {
            this.clusterCaCertificate = Objects.requireNonNull(clusterCaCertificate);
            return this;
        }
        @CustomType.Setter
        public Builder configFile(String configFile) {
            this.configFile = Objects.requireNonNull(configFile);
            return this;
        }
        @CustomType.Setter
        public Builder host(String host) {
            this.host = Objects.requireNonNull(host);
            return this;
        }
        @CustomType.Setter
        public Builder token(String token) {
            this.token = Objects.requireNonNull(token);
            return this;
        }
        public GetK8sClusterKubeconfig build() {
            final var o = new GetK8sClusterKubeconfig();
            o.clusterCaCertificate = clusterCaCertificate;
            o.configFile = configFile;
            o.host = host;
            o.token = token;
            return o;
        }
    }
}
