// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.scaleway.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class LbFrontendAclAction {
    /**
     * @return The action type. Possible values are: `allow` or `deny`.
     * 
     */
    private String type;

    private LbFrontendAclAction() {}
    /**
     * @return The action type. Possible values are: `allow` or `deny`.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LbFrontendAclAction defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String type;
        public Builder() {}
        public Builder(LbFrontendAclAction defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        public LbFrontendAclAction build() {
            final var o = new LbFrontendAclAction();
            o.type = type;
            return o;
        }
    }
}
