// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Scaleway.Outputs
{

    [OutputType]
    public sealed class LbCertificateLetsencrypt
    {
        /// <summary>
        /// Main domain of the certificate
        /// </summary>
        public readonly string CommonName;
        /// <summary>
        /// The alternative domain names of the certificate
        /// </summary>
        public readonly ImmutableArray<string> SubjectAlternativeNames;

        [OutputConstructor]
        private LbCertificateLetsencrypt(
            string commonName,

            ImmutableArray<string> subjectAlternativeNames)
        {
            CommonName = commonName;
            SubjectAlternativeNames = subjectAlternativeNames;
        }
    }
}
