// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Gets information about a Load Balancer IP.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/dirien/pulumi-scaleway/sdk/v2/go/scaleway"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := scaleway.LookupLbIp(ctx, &scaleway.LookupLbIpArgs{
//				IpId: pulumi.StringRef("11111111-1111-1111-1111-111111111111"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupLbIp(ctx *pulumi.Context, args *LookupLbIpArgs, opts ...pulumi.InvokeOption) (*LookupLbIpResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupLbIpResult
	err := ctx.Invoke("scaleway:index/getLbIp:getLbIp", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLbIp.
type LookupLbIpArgs struct {
	// The IP address.
	// Only one of `ipAddress` and `ipId` should be specified.
	IpAddress *string `pulumi:"ipAddress"`
	// The IP ID.
	// Only one of `ipAddress` and `ipId` should be specified.
	IpId *string `pulumi:"ipId"`
}

// A collection of values returned by getLbIp.
type LookupLbIpResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id        string  `pulumi:"id"`
	IpAddress *string `pulumi:"ipAddress"`
	IpId      *string `pulumi:"ipId"`
	// The associated load-balancer ID if any
	LbId string `pulumi:"lbId"`
	// (Defaults to provider `organizationId`) The ID of the organization the LB IP is associated with.
	OrganizationId string `pulumi:"organizationId"`
	ProjectId      string `pulumi:"projectId"`
	Region         string `pulumi:"region"`
	// The reverse domain associated with this IP.
	Reverse string `pulumi:"reverse"`
	Zone    string `pulumi:"zone"`
}

func LookupLbIpOutput(ctx *pulumi.Context, args LookupLbIpOutputArgs, opts ...pulumi.InvokeOption) LookupLbIpResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupLbIpResult, error) {
			args := v.(LookupLbIpArgs)
			r, err := LookupLbIp(ctx, &args, opts...)
			var s LookupLbIpResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupLbIpResultOutput)
}

// A collection of arguments for invoking getLbIp.
type LookupLbIpOutputArgs struct {
	// The IP address.
	// Only one of `ipAddress` and `ipId` should be specified.
	IpAddress pulumi.StringPtrInput `pulumi:"ipAddress"`
	// The IP ID.
	// Only one of `ipAddress` and `ipId` should be specified.
	IpId pulumi.StringPtrInput `pulumi:"ipId"`
}

func (LookupLbIpOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLbIpArgs)(nil)).Elem()
}

// A collection of values returned by getLbIp.
type LookupLbIpResultOutput struct{ *pulumi.OutputState }

func (LookupLbIpResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLbIpResult)(nil)).Elem()
}

func (o LookupLbIpResultOutput) ToLookupLbIpResultOutput() LookupLbIpResultOutput {
	return o
}

func (o LookupLbIpResultOutput) ToLookupLbIpResultOutputWithContext(ctx context.Context) LookupLbIpResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupLbIpResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbIpResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupLbIpResultOutput) IpAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupLbIpResult) *string { return v.IpAddress }).(pulumi.StringPtrOutput)
}

func (o LookupLbIpResultOutput) IpId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupLbIpResult) *string { return v.IpId }).(pulumi.StringPtrOutput)
}

// The associated load-balancer ID if any
func (o LookupLbIpResultOutput) LbId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbIpResult) string { return v.LbId }).(pulumi.StringOutput)
}

// (Defaults to provider `organizationId`) The ID of the organization the LB IP is associated with.
func (o LookupLbIpResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbIpResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

func (o LookupLbIpResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbIpResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

func (o LookupLbIpResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbIpResult) string { return v.Region }).(pulumi.StringOutput)
}

// The reverse domain associated with this IP.
func (o LookupLbIpResultOutput) Reverse() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbIpResult) string { return v.Reverse }).(pulumi.StringOutput)
}

func (o LookupLbIpResultOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLbIpResult) string { return v.Zone }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupLbIpResultOutput{})
}
