// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"context"
	"reflect"

	"github.com/dirien/pulumi-scaleway/sdk/v2/go/scaleway/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// Gets information about a webhosting.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/dirien/pulumi-scaleway/sdk/v2/go/scaleway"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := scaleway.GetWebhosting(ctx, &scaleway.GetWebhostingArgs{
//				Domain: pulumi.StringRef("foobar.com"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = scaleway.GetWebhosting(ctx, &scaleway.GetWebhostingArgs{
//				WebhostingId: pulumi.StringRef("11111111-1111-1111-1111-111111111111"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetWebhosting(ctx *pulumi.Context, args *GetWebhostingArgs, opts ...pulumi.InvokeOption) (*GetWebhostingResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetWebhostingResult
	err := ctx.Invoke("scaleway:index/getWebhosting:getWebhosting", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getWebhosting.
type GetWebhostingArgs struct {
	// The hosting domain name. Only one of `domain` and `webhostingId` should be specified.
	Domain *string `pulumi:"domain"`
	// The ID of the organization the hosting is associated with.
	OrganizationId *string `pulumi:"organizationId"`
	// `projectId`) The ID of the project the hosting is associated with.
	ProjectId *string `pulumi:"projectId"`
	// The hosting id. Only one of `domain` and `webhostingId` should be specified.
	WebhostingId *string `pulumi:"webhostingId"`
}

// A collection of values returned by getWebhosting.
type GetWebhostingResult struct {
	CpanelUrls []GetWebhostingCpanelUrl `pulumi:"cpanelUrls"`
	CreatedAt  string                   `pulumi:"createdAt"`
	DnsStatus  string                   `pulumi:"dnsStatus"`
	Domain     *string                  `pulumi:"domain"`
	Email      string                   `pulumi:"email"`
	// The provider-assigned unique ID for this managed resource.
	Id               string                `pulumi:"id"`
	OfferId          string                `pulumi:"offerId"`
	OfferName        string                `pulumi:"offerName"`
	OptionIds        []string              `pulumi:"optionIds"`
	Options          []GetWebhostingOption `pulumi:"options"`
	OrganizationId   string                `pulumi:"organizationId"`
	PlatformHostname string                `pulumi:"platformHostname"`
	PlatformNumber   int                   `pulumi:"platformNumber"`
	ProjectId        *string               `pulumi:"projectId"`
	Region           string                `pulumi:"region"`
	Status           string                `pulumi:"status"`
	Tags             []string              `pulumi:"tags"`
	UpdatedAt        string                `pulumi:"updatedAt"`
	Username         string                `pulumi:"username"`
	WebhostingId     *string               `pulumi:"webhostingId"`
}

func GetWebhostingOutput(ctx *pulumi.Context, args GetWebhostingOutputArgs, opts ...pulumi.InvokeOption) GetWebhostingResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetWebhostingResult, error) {
			args := v.(GetWebhostingArgs)
			r, err := GetWebhosting(ctx, &args, opts...)
			var s GetWebhostingResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetWebhostingResultOutput)
}

// A collection of arguments for invoking getWebhosting.
type GetWebhostingOutputArgs struct {
	// The hosting domain name. Only one of `domain` and `webhostingId` should be specified.
	Domain pulumi.StringPtrInput `pulumi:"domain"`
	// The ID of the organization the hosting is associated with.
	OrganizationId pulumi.StringPtrInput `pulumi:"organizationId"`
	// `projectId`) The ID of the project the hosting is associated with.
	ProjectId pulumi.StringPtrInput `pulumi:"projectId"`
	// The hosting id. Only one of `domain` and `webhostingId` should be specified.
	WebhostingId pulumi.StringPtrInput `pulumi:"webhostingId"`
}

func (GetWebhostingOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetWebhostingArgs)(nil)).Elem()
}

// A collection of values returned by getWebhosting.
type GetWebhostingResultOutput struct{ *pulumi.OutputState }

func (GetWebhostingResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetWebhostingResult)(nil)).Elem()
}

func (o GetWebhostingResultOutput) ToGetWebhostingResultOutput() GetWebhostingResultOutput {
	return o
}

func (o GetWebhostingResultOutput) ToGetWebhostingResultOutputWithContext(ctx context.Context) GetWebhostingResultOutput {
	return o
}

func (o GetWebhostingResultOutput) ToOutput(ctx context.Context) pulumix.Output[GetWebhostingResult] {
	return pulumix.Output[GetWebhostingResult]{
		OutputState: o.OutputState,
	}
}

func (o GetWebhostingResultOutput) CpanelUrls() GetWebhostingCpanelUrlArrayOutput {
	return o.ApplyT(func(v GetWebhostingResult) []GetWebhostingCpanelUrl { return v.CpanelUrls }).(GetWebhostingCpanelUrlArrayOutput)
}

func (o GetWebhostingResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetWebhostingResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o GetWebhostingResultOutput) DnsStatus() pulumi.StringOutput {
	return o.ApplyT(func(v GetWebhostingResult) string { return v.DnsStatus }).(pulumi.StringOutput)
}

func (o GetWebhostingResultOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetWebhostingResult) *string { return v.Domain }).(pulumi.StringPtrOutput)
}

func (o GetWebhostingResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v GetWebhostingResult) string { return v.Email }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetWebhostingResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetWebhostingResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetWebhostingResultOutput) OfferId() pulumi.StringOutput {
	return o.ApplyT(func(v GetWebhostingResult) string { return v.OfferId }).(pulumi.StringOutput)
}

func (o GetWebhostingResultOutput) OfferName() pulumi.StringOutput {
	return o.ApplyT(func(v GetWebhostingResult) string { return v.OfferName }).(pulumi.StringOutput)
}

func (o GetWebhostingResultOutput) OptionIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetWebhostingResult) []string { return v.OptionIds }).(pulumi.StringArrayOutput)
}

func (o GetWebhostingResultOutput) Options() GetWebhostingOptionArrayOutput {
	return o.ApplyT(func(v GetWebhostingResult) []GetWebhostingOption { return v.Options }).(GetWebhostingOptionArrayOutput)
}

func (o GetWebhostingResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v GetWebhostingResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

func (o GetWebhostingResultOutput) PlatformHostname() pulumi.StringOutput {
	return o.ApplyT(func(v GetWebhostingResult) string { return v.PlatformHostname }).(pulumi.StringOutput)
}

func (o GetWebhostingResultOutput) PlatformNumber() pulumi.IntOutput {
	return o.ApplyT(func(v GetWebhostingResult) int { return v.PlatformNumber }).(pulumi.IntOutput)
}

func (o GetWebhostingResultOutput) ProjectId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetWebhostingResult) *string { return v.ProjectId }).(pulumi.StringPtrOutput)
}

func (o GetWebhostingResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetWebhostingResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetWebhostingResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetWebhostingResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o GetWebhostingResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetWebhostingResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

func (o GetWebhostingResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetWebhostingResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func (o GetWebhostingResultOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v GetWebhostingResult) string { return v.Username }).(pulumi.StringOutput)
}

func (o GetWebhostingResultOutput) WebhostingId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetWebhostingResult) *string { return v.WebhostingId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetWebhostingResultOutput{})
}
