// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"context"
	"reflect"

	"errors"
	"github.com/dirien/pulumi-scaleway/sdk/v2/go/scaleway/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates and manages Scaleway Load Balancer frontends.
//
// For more information, see the [main documentation](https://www.scaleway.com/en/docs/load-balancer/reference-content/configuring-frontends/) or [API documentation](https://www.scaleway.com/en/developers/api/load-balancer/zoned-api/#path-frontends).
//
// ## Example Usage
//
// ### Basic
//
// ```go
// package main
//
// import (
//
//	"github.com/dirien/pulumi-scaleway/sdk/v2/go/scaleway"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := scaleway.NewLbFrontend(ctx, "frontend01", &scaleway.LbFrontendArgs{
//				LbId:        pulumi.Any(scaleway_lb.Lb01.Id),
//				BackendId:   pulumi.Any(scaleway_lb_backend.Backend01.Id),
//				InboundPort: pulumi.Int(80),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## With ACLs
//
// ```go
// package main
//
// import (
//
//	"github.com/dirien/pulumi-scaleway/sdk/v2/go/scaleway"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := scaleway.NewLbFrontend(ctx, "frontend01", &scaleway.LbFrontendArgs{
//				LbId:        pulumi.Any(scaleway_lb.Lb01.Id),
//				BackendId:   pulumi.Any(scaleway_lb_backend.Backend01.Id),
//				InboundPort: pulumi.Int(80),
//				Acls: scaleway.LbFrontendAclArray{
//					&scaleway.LbFrontendAclArgs{
//						Name: pulumi.String("blacklist wellknwon IPs"),
//						Action: &scaleway.LbFrontendAclActionArgs{
//							Type: pulumi.String("allow"),
//						},
//						Match: &scaleway.LbFrontendAclMatchArgs{
//							IpSubnets: pulumi.StringArray{
//								pulumi.String("192.168.0.1"),
//								pulumi.String("192.168.0.2"),
//								pulumi.String("192.168.10.0/24"),
//							},
//						},
//					},
//					&scaleway.LbFrontendAclArgs{
//						Action: &scaleway.LbFrontendAclActionArgs{
//							Type: pulumi.String("deny"),
//						},
//						Match: &scaleway.LbFrontendAclMatchArgs{
//							IpSubnets: pulumi.StringArray{
//								pulumi.String("51.51.51.51"),
//							},
//							HttpFilter: pulumi.String("regex"),
//							HttpFilterValues: pulumi.StringArray{
//								pulumi.String("^foo*bar$"),
//							},
//						},
//					},
//					&scaleway.LbFrontendAclArgs{
//						Action: &scaleway.LbFrontendAclActionArgs{
//							Type: pulumi.String("allow"),
//						},
//						Match: &scaleway.LbFrontendAclMatchArgs{
//							HttpFilter: pulumi.String("path_begin"),
//							HttpFilterValues: pulumi.StringArray{
//								pulumi.String("foo"),
//								pulumi.String("bar"),
//							},
//						},
//					},
//					&scaleway.LbFrontendAclArgs{
//						Action: &scaleway.LbFrontendAclActionArgs{
//							Type: pulumi.String("allow"),
//						},
//						Match: &scaleway.LbFrontendAclMatchArgs{
//							HttpFilter: pulumi.String("path_begin"),
//							HttpFilterValues: pulumi.StringArray{
//								pulumi.String("hi"),
//							},
//							Invert: pulumi.Bool(true),
//						},
//					},
//					&scaleway.LbFrontendAclArgs{
//						Action: &scaleway.LbFrontendAclActionArgs{
//							Type: pulumi.String("allow"),
//						},
//						Match: &scaleway.LbFrontendAclMatchArgs{
//							HttpFilter:       pulumi.String("http_header_match"),
//							HttpFilterValues: pulumi.StringArray("foo"),
//							HttpFilterOption: pulumi.String("bar"),
//						},
//					},
//					&scaleway.LbFrontendAclArgs{
//						Action: &scaleway.LbFrontendAclActionArgs{
//							Type: pulumi.String("redirect"),
//							Redirects: scaleway.LbFrontendAclActionRedirectArray{
//								&scaleway.LbFrontendAclActionRedirectArgs{
//									Type:   pulumi.String("location"),
//									Target: pulumi.String("https://example.com"),
//									Code:   pulumi.Int(307),
//								},
//							},
//						},
//						Match: &scaleway.LbFrontendAclMatchArgs{
//							IpSubnets: pulumi.StringArray{
//								pulumi.String("10.0.0.10"),
//							},
//							HttpFilter: pulumi.String("path_begin"),
//							HttpFilterValues: pulumi.StringArray{
//								pulumi.String("foo"),
//								pulumi.String("bar"),
//							},
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// Load Balancer frontends can be imported using `{zone}/{id}`, e.g.
//
// bash
//
// ```sh
// $ pulumi import scaleway:index/lbFrontend:LbFrontend frontend01 fr-par-1/11111111-1111-1111-1111-111111111111
// ```
type LbFrontend struct {
	pulumi.CustomResourceState

	// A list of ACL rules to apply to the Load Balancer frontend.  Defined below.
	Acls LbFrontendAclArrayOutput `pulumi:"acls"`
	// The ID of the Load Balancer backend this frontend is attached to.
	//
	// > **Important:** Updates to `lbId` or `backendId` will recreate the frontend.
	BackendId pulumi.StringOutput `pulumi:"backendId"`
	// (Deprecated, use `certificateIds` instead) First certificate ID used by the frontend.
	//
	// Deprecated: Please use certificate_ids
	CertificateId pulumi.StringOutput `pulumi:"certificateId"`
	// List of certificate IDs that should be used by the frontend.
	//
	// > **Important:** Certificates are not allowed on port 80.
	CertificateIds pulumi.StringArrayOutput `pulumi:"certificateIds"`
	// The rate limit for new connections established on this frontend. Use 0 value to disable, else value is connections per second.
	ConnectionRateLimit pulumi.IntPtrOutput `pulumi:"connectionRateLimit"`
	// Activates HTTP/3 protocol.
	EnableHttp3 pulumi.BoolPtrOutput `pulumi:"enableHttp3"`
	// A boolean to specify whether to use lb_acl.
	// If `externalAcls` is set to `true`, `acl` can not be set directly in the Load Balancer frontend.
	ExternalAcls pulumi.BoolPtrOutput `pulumi:"externalAcls"`
	// TCP port to listen to on the front side.
	InboundPort pulumi.IntOutput `pulumi:"inboundPort"`
	// The ID of the Load Balancer this frontend is attached to.
	LbId pulumi.StringOutput `pulumi:"lbId"`
	// The ACL name. If not provided it will be randomly generated.
	Name pulumi.StringOutput `pulumi:"name"`
	// Maximum inactivity time on the client side. (e.g. `1s`)
	TimeoutClient pulumi.StringPtrOutput `pulumi:"timeoutClient"`
}

// NewLbFrontend registers a new resource with the given unique name, arguments, and options.
func NewLbFrontend(ctx *pulumi.Context,
	name string, args *LbFrontendArgs, opts ...pulumi.ResourceOption) (*LbFrontend, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.BackendId == nil {
		return nil, errors.New("invalid value for required argument 'BackendId'")
	}
	if args.InboundPort == nil {
		return nil, errors.New("invalid value for required argument 'InboundPort'")
	}
	if args.LbId == nil {
		return nil, errors.New("invalid value for required argument 'LbId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource LbFrontend
	err := ctx.RegisterResource("scaleway:index/lbFrontend:LbFrontend", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLbFrontend gets an existing LbFrontend resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLbFrontend(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LbFrontendState, opts ...pulumi.ResourceOption) (*LbFrontend, error) {
	var resource LbFrontend
	err := ctx.ReadResource("scaleway:index/lbFrontend:LbFrontend", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LbFrontend resources.
type lbFrontendState struct {
	// A list of ACL rules to apply to the Load Balancer frontend.  Defined below.
	Acls []LbFrontendAcl `pulumi:"acls"`
	// The ID of the Load Balancer backend this frontend is attached to.
	//
	// > **Important:** Updates to `lbId` or `backendId` will recreate the frontend.
	BackendId *string `pulumi:"backendId"`
	// (Deprecated, use `certificateIds` instead) First certificate ID used by the frontend.
	//
	// Deprecated: Please use certificate_ids
	CertificateId *string `pulumi:"certificateId"`
	// List of certificate IDs that should be used by the frontend.
	//
	// > **Important:** Certificates are not allowed on port 80.
	CertificateIds []string `pulumi:"certificateIds"`
	// The rate limit for new connections established on this frontend. Use 0 value to disable, else value is connections per second.
	ConnectionRateLimit *int `pulumi:"connectionRateLimit"`
	// Activates HTTP/3 protocol.
	EnableHttp3 *bool `pulumi:"enableHttp3"`
	// A boolean to specify whether to use lb_acl.
	// If `externalAcls` is set to `true`, `acl` can not be set directly in the Load Balancer frontend.
	ExternalAcls *bool `pulumi:"externalAcls"`
	// TCP port to listen to on the front side.
	InboundPort *int `pulumi:"inboundPort"`
	// The ID of the Load Balancer this frontend is attached to.
	LbId *string `pulumi:"lbId"`
	// The ACL name. If not provided it will be randomly generated.
	Name *string `pulumi:"name"`
	// Maximum inactivity time on the client side. (e.g. `1s`)
	TimeoutClient *string `pulumi:"timeoutClient"`
}

type LbFrontendState struct {
	// A list of ACL rules to apply to the Load Balancer frontend.  Defined below.
	Acls LbFrontendAclArrayInput
	// The ID of the Load Balancer backend this frontend is attached to.
	//
	// > **Important:** Updates to `lbId` or `backendId` will recreate the frontend.
	BackendId pulumi.StringPtrInput
	// (Deprecated, use `certificateIds` instead) First certificate ID used by the frontend.
	//
	// Deprecated: Please use certificate_ids
	CertificateId pulumi.StringPtrInput
	// List of certificate IDs that should be used by the frontend.
	//
	// > **Important:** Certificates are not allowed on port 80.
	CertificateIds pulumi.StringArrayInput
	// The rate limit for new connections established on this frontend. Use 0 value to disable, else value is connections per second.
	ConnectionRateLimit pulumi.IntPtrInput
	// Activates HTTP/3 protocol.
	EnableHttp3 pulumi.BoolPtrInput
	// A boolean to specify whether to use lb_acl.
	// If `externalAcls` is set to `true`, `acl` can not be set directly in the Load Balancer frontend.
	ExternalAcls pulumi.BoolPtrInput
	// TCP port to listen to on the front side.
	InboundPort pulumi.IntPtrInput
	// The ID of the Load Balancer this frontend is attached to.
	LbId pulumi.StringPtrInput
	// The ACL name. If not provided it will be randomly generated.
	Name pulumi.StringPtrInput
	// Maximum inactivity time on the client side. (e.g. `1s`)
	TimeoutClient pulumi.StringPtrInput
}

func (LbFrontendState) ElementType() reflect.Type {
	return reflect.TypeOf((*lbFrontendState)(nil)).Elem()
}

type lbFrontendArgs struct {
	// A list of ACL rules to apply to the Load Balancer frontend.  Defined below.
	Acls []LbFrontendAcl `pulumi:"acls"`
	// The ID of the Load Balancer backend this frontend is attached to.
	//
	// > **Important:** Updates to `lbId` or `backendId` will recreate the frontend.
	BackendId string `pulumi:"backendId"`
	// List of certificate IDs that should be used by the frontend.
	//
	// > **Important:** Certificates are not allowed on port 80.
	CertificateIds []string `pulumi:"certificateIds"`
	// The rate limit for new connections established on this frontend. Use 0 value to disable, else value is connections per second.
	ConnectionRateLimit *int `pulumi:"connectionRateLimit"`
	// Activates HTTP/3 protocol.
	EnableHttp3 *bool `pulumi:"enableHttp3"`
	// A boolean to specify whether to use lb_acl.
	// If `externalAcls` is set to `true`, `acl` can not be set directly in the Load Balancer frontend.
	ExternalAcls *bool `pulumi:"externalAcls"`
	// TCP port to listen to on the front side.
	InboundPort int `pulumi:"inboundPort"`
	// The ID of the Load Balancer this frontend is attached to.
	LbId string `pulumi:"lbId"`
	// The ACL name. If not provided it will be randomly generated.
	Name *string `pulumi:"name"`
	// Maximum inactivity time on the client side. (e.g. `1s`)
	TimeoutClient *string `pulumi:"timeoutClient"`
}

// The set of arguments for constructing a LbFrontend resource.
type LbFrontendArgs struct {
	// A list of ACL rules to apply to the Load Balancer frontend.  Defined below.
	Acls LbFrontendAclArrayInput
	// The ID of the Load Balancer backend this frontend is attached to.
	//
	// > **Important:** Updates to `lbId` or `backendId` will recreate the frontend.
	BackendId pulumi.StringInput
	// List of certificate IDs that should be used by the frontend.
	//
	// > **Important:** Certificates are not allowed on port 80.
	CertificateIds pulumi.StringArrayInput
	// The rate limit for new connections established on this frontend. Use 0 value to disable, else value is connections per second.
	ConnectionRateLimit pulumi.IntPtrInput
	// Activates HTTP/3 protocol.
	EnableHttp3 pulumi.BoolPtrInput
	// A boolean to specify whether to use lb_acl.
	// If `externalAcls` is set to `true`, `acl` can not be set directly in the Load Balancer frontend.
	ExternalAcls pulumi.BoolPtrInput
	// TCP port to listen to on the front side.
	InboundPort pulumi.IntInput
	// The ID of the Load Balancer this frontend is attached to.
	LbId pulumi.StringInput
	// The ACL name. If not provided it will be randomly generated.
	Name pulumi.StringPtrInput
	// Maximum inactivity time on the client side. (e.g. `1s`)
	TimeoutClient pulumi.StringPtrInput
}

func (LbFrontendArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*lbFrontendArgs)(nil)).Elem()
}

type LbFrontendInput interface {
	pulumi.Input

	ToLbFrontendOutput() LbFrontendOutput
	ToLbFrontendOutputWithContext(ctx context.Context) LbFrontendOutput
}

func (*LbFrontend) ElementType() reflect.Type {
	return reflect.TypeOf((**LbFrontend)(nil)).Elem()
}

func (i *LbFrontend) ToLbFrontendOutput() LbFrontendOutput {
	return i.ToLbFrontendOutputWithContext(context.Background())
}

func (i *LbFrontend) ToLbFrontendOutputWithContext(ctx context.Context) LbFrontendOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LbFrontendOutput)
}

// LbFrontendArrayInput is an input type that accepts LbFrontendArray and LbFrontendArrayOutput values.
// You can construct a concrete instance of `LbFrontendArrayInput` via:
//
//	LbFrontendArray{ LbFrontendArgs{...} }
type LbFrontendArrayInput interface {
	pulumi.Input

	ToLbFrontendArrayOutput() LbFrontendArrayOutput
	ToLbFrontendArrayOutputWithContext(context.Context) LbFrontendArrayOutput
}

type LbFrontendArray []LbFrontendInput

func (LbFrontendArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LbFrontend)(nil)).Elem()
}

func (i LbFrontendArray) ToLbFrontendArrayOutput() LbFrontendArrayOutput {
	return i.ToLbFrontendArrayOutputWithContext(context.Background())
}

func (i LbFrontendArray) ToLbFrontendArrayOutputWithContext(ctx context.Context) LbFrontendArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LbFrontendArrayOutput)
}

// LbFrontendMapInput is an input type that accepts LbFrontendMap and LbFrontendMapOutput values.
// You can construct a concrete instance of `LbFrontendMapInput` via:
//
//	LbFrontendMap{ "key": LbFrontendArgs{...} }
type LbFrontendMapInput interface {
	pulumi.Input

	ToLbFrontendMapOutput() LbFrontendMapOutput
	ToLbFrontendMapOutputWithContext(context.Context) LbFrontendMapOutput
}

type LbFrontendMap map[string]LbFrontendInput

func (LbFrontendMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LbFrontend)(nil)).Elem()
}

func (i LbFrontendMap) ToLbFrontendMapOutput() LbFrontendMapOutput {
	return i.ToLbFrontendMapOutputWithContext(context.Background())
}

func (i LbFrontendMap) ToLbFrontendMapOutputWithContext(ctx context.Context) LbFrontendMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LbFrontendMapOutput)
}

type LbFrontendOutput struct{ *pulumi.OutputState }

func (LbFrontendOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LbFrontend)(nil)).Elem()
}

func (o LbFrontendOutput) ToLbFrontendOutput() LbFrontendOutput {
	return o
}

func (o LbFrontendOutput) ToLbFrontendOutputWithContext(ctx context.Context) LbFrontendOutput {
	return o
}

// A list of ACL rules to apply to the Load Balancer frontend.  Defined below.
func (o LbFrontendOutput) Acls() LbFrontendAclArrayOutput {
	return o.ApplyT(func(v *LbFrontend) LbFrontendAclArrayOutput { return v.Acls }).(LbFrontendAclArrayOutput)
}

// The ID of the Load Balancer backend this frontend is attached to.
//
// > **Important:** Updates to `lbId` or `backendId` will recreate the frontend.
func (o LbFrontendOutput) BackendId() pulumi.StringOutput {
	return o.ApplyT(func(v *LbFrontend) pulumi.StringOutput { return v.BackendId }).(pulumi.StringOutput)
}

// (Deprecated, use `certificateIds` instead) First certificate ID used by the frontend.
//
// Deprecated: Please use certificate_ids
func (o LbFrontendOutput) CertificateId() pulumi.StringOutput {
	return o.ApplyT(func(v *LbFrontend) pulumi.StringOutput { return v.CertificateId }).(pulumi.StringOutput)
}

// List of certificate IDs that should be used by the frontend.
//
// > **Important:** Certificates are not allowed on port 80.
func (o LbFrontendOutput) CertificateIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *LbFrontend) pulumi.StringArrayOutput { return v.CertificateIds }).(pulumi.StringArrayOutput)
}

// The rate limit for new connections established on this frontend. Use 0 value to disable, else value is connections per second.
func (o LbFrontendOutput) ConnectionRateLimit() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *LbFrontend) pulumi.IntPtrOutput { return v.ConnectionRateLimit }).(pulumi.IntPtrOutput)
}

// Activates HTTP/3 protocol.
func (o LbFrontendOutput) EnableHttp3() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *LbFrontend) pulumi.BoolPtrOutput { return v.EnableHttp3 }).(pulumi.BoolPtrOutput)
}

// A boolean to specify whether to use lb_acl.
// If `externalAcls` is set to `true`, `acl` can not be set directly in the Load Balancer frontend.
func (o LbFrontendOutput) ExternalAcls() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *LbFrontend) pulumi.BoolPtrOutput { return v.ExternalAcls }).(pulumi.BoolPtrOutput)
}

// TCP port to listen to on the front side.
func (o LbFrontendOutput) InboundPort() pulumi.IntOutput {
	return o.ApplyT(func(v *LbFrontend) pulumi.IntOutput { return v.InboundPort }).(pulumi.IntOutput)
}

// The ID of the Load Balancer this frontend is attached to.
func (o LbFrontendOutput) LbId() pulumi.StringOutput {
	return o.ApplyT(func(v *LbFrontend) pulumi.StringOutput { return v.LbId }).(pulumi.StringOutput)
}

// The ACL name. If not provided it will be randomly generated.
func (o LbFrontendOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *LbFrontend) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Maximum inactivity time on the client side. (e.g. `1s`)
func (o LbFrontendOutput) TimeoutClient() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LbFrontend) pulumi.StringPtrOutput { return v.TimeoutClient }).(pulumi.StringPtrOutput)
}

type LbFrontendArrayOutput struct{ *pulumi.OutputState }

func (LbFrontendArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LbFrontend)(nil)).Elem()
}

func (o LbFrontendArrayOutput) ToLbFrontendArrayOutput() LbFrontendArrayOutput {
	return o
}

func (o LbFrontendArrayOutput) ToLbFrontendArrayOutputWithContext(ctx context.Context) LbFrontendArrayOutput {
	return o
}

func (o LbFrontendArrayOutput) Index(i pulumi.IntInput) LbFrontendOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *LbFrontend {
		return vs[0].([]*LbFrontend)[vs[1].(int)]
	}).(LbFrontendOutput)
}

type LbFrontendMapOutput struct{ *pulumi.OutputState }

func (LbFrontendMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LbFrontend)(nil)).Elem()
}

func (o LbFrontendMapOutput) ToLbFrontendMapOutput() LbFrontendMapOutput {
	return o
}

func (o LbFrontendMapOutput) ToLbFrontendMapOutputWithContext(ctx context.Context) LbFrontendMapOutput {
	return o
}

func (o LbFrontendMapOutput) MapIndex(k pulumi.StringInput) LbFrontendOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *LbFrontend {
		return vs[0].(map[string]*LbFrontend)[vs[1].(string)]
	}).(LbFrontendOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LbFrontendInput)(nil)).Elem(), &LbFrontend{})
	pulumi.RegisterInputType(reflect.TypeOf((*LbFrontendArrayInput)(nil)).Elem(), LbFrontendArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*LbFrontendMapInput)(nil)).Elem(), LbFrontendMap{})
	pulumi.RegisterOutputType(LbFrontendOutput{})
	pulumi.RegisterOutputType(LbFrontendArrayOutput{})
	pulumi.RegisterOutputType(LbFrontendMapOutput{})
}
