// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Scaleway.Inputs
{

    public sealed class DocumentDBReadReplicaPrivateNetworkArgs : global::Pulumi.ResourceArgs
    {
        [Input("endpointId")]
        public Input<string>? EndpointId { get; set; }

        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        [Input("ip")]
        public Input<string>? Ip { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("port")]
        public Input<int>? Port { get; set; }

        [Input("privateNetworkId", required: true)]
        public Input<string> PrivateNetworkId { get; set; } = null!;

        [Input("serviceIp")]
        public Input<string>? ServiceIp { get; set; }

        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public DocumentDBReadReplicaPrivateNetworkArgs()
        {
        }
        public static new DocumentDBReadReplicaPrivateNetworkArgs Empty => new DocumentDBReadReplicaPrivateNetworkArgs();
    }
}
