// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Scaleway.Inputs
{

    public sealed class DomainRegistrationTechnicalContactExtensionEuArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Indicates the European citizenship of the contact.
        /// </summary>
        [Input("europeanCitizenship")]
        public Input<string>? EuropeanCitizenship { get; set; }

        public DomainRegistrationTechnicalContactExtensionEuArgs()
        {
        }
        public static new DomainRegistrationTechnicalContactExtensionEuArgs Empty => new DomainRegistrationTechnicalContactExtensionEuArgs();
    }
}
