// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Scaleway.Inputs
{

    public sealed class DomainRegistrationOwnerContactExtensionFrArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Association-specific information for the domain (French extension).
        /// </summary>
        [Input("associationInfo")]
        public Input<Inputs.DomainRegistrationOwnerContactExtensionFrAssociationInfoArgs>? AssociationInfo { get; set; }

        /// <summary>
        /// AFNIC authorization information for the contact (French extension).
        /// </summary>
        [Input("codeAuthAfnicInfo")]
        public Input<Inputs.DomainRegistrationOwnerContactExtensionFrCodeAuthAfnicInfoArgs>? CodeAuthAfnicInfo { get; set; }

        /// <summary>
        /// DUNS information for the domain owner (specific to French domains).
        /// </summary>
        [Input("dunsInfo")]
        public Input<Inputs.DomainRegistrationOwnerContactExtensionFrDunsInfoArgs>? DunsInfo { get; set; }

        /// <summary>
        /// Information about the individual registration for French domains.
        /// </summary>
        [Input("individualInfo")]
        public Input<Inputs.DomainRegistrationOwnerContactExtensionFrIndividualInfoArgs>? IndividualInfo { get; set; }

        /// <summary>
        /// Mode of the French extension (e.g., 'individual', 'duns', 'association', etc.).
        /// </summary>
        [Input("mode")]
        public Input<string>? Mode { get; set; }

        /// <summary>
        /// Trademark-related information for the domain (French extension).
        /// </summary>
        [Input("trademarkInfo")]
        public Input<Inputs.DomainRegistrationOwnerContactExtensionFrTrademarkInfoArgs>? TrademarkInfo { get; set; }

        public DomainRegistrationOwnerContactExtensionFrArgs()
        {
        }
        public static new DomainRegistrationOwnerContactExtensionFrArgs Empty => new DomainRegistrationOwnerContactExtensionFrArgs();
    }
}
