// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Scaleway.Inputs
{

    public sealed class InferenceModelNodesSupportArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The type of node supported.
        /// </summary>
        [Input("nodeTypeName")]
        public Input<string>? NodeTypeName { get; set; }

        [Input("quantizations")]
        private InputList<Inputs.InferenceModelNodesSupportQuantizationArgs>? _quantizations;

        /// <summary>
        /// A list of supported quantization options, including:
        /// </summary>
        public InputList<Inputs.InferenceModelNodesSupportQuantizationArgs> Quantizations
        {
            get => _quantizations ?? (_quantizations = new InputList<Inputs.InferenceModelNodesSupportQuantizationArgs>());
            set => _quantizations = value;
        }

        public InferenceModelNodesSupportArgs()
        {
        }
        public static new InferenceModelNodesSupportArgs Empty => new InferenceModelNodesSupportArgs();
    }
}
