// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The `scaleway.getAccountProjects` data source is used to list all Scaleway projects in an Organization.
 *
 * Refer to the Organizations and Projects [documentation](https://www.scaleway.com/en/docs/organizations-and-projects/) and [API documentation](https://www.scaleway.com/en/developers/api/account/project-api/) for more information.
 *
 * ## Retrieve a Scaleway Projects
 *
 * The following commands allow you to:
 *
 * - retrieve all Projects in an Organization
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@ediri/scaleway";
 *
 * const all = scaleway.getAccountProjects({
 *     organizationId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
 * });
 * ```
 *
 * ## Example Usage
 *
 * ### Deploy an SSH key in all your organization's projects
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@ediri/scaleway";
 *
 * const all = scaleway.getAccountProjects({});
 * const main: scaleway.AccountSshKey[] = [];
 * all.then(all => all.projects).length.apply(rangeBody => {
 *     for (const range = {value: 0}; range.value < rangeBody; range.value++) {
 *         main.push(new scaleway.AccountSshKey(`main-${range.value}`, {
 *             publicKey: local.public_key,
 *             projectId: all.then(all => all.projects[range.value].id),
 *         }));
 *     }
 * });
 * ```
 */
export function getAccountProjects(args?: GetAccountProjectsArgs, opts?: pulumi.InvokeOptions): Promise<GetAccountProjectsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("scaleway:index/getAccountProjects:getAccountProjects", {
        "organizationId": args.organizationId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAccountProjects.
 */
export interface GetAccountProjectsArgs {
    /**
     * The unique identifier of the Organization with which the Projects are associated.
     * If no default `organizationId` is set, one must be set explicitly in this datasource
     */
    organizationId?: string;
}

/**
 * A collection of values returned by getAccountProjects.
 */
export interface GetAccountProjectsResult {
    /**
     * (Computed) The date and time when the project was created.
     */
    readonly createdAt: string;
    /**
     * (Computed) The description of the project.
     */
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * (Computed) The name of the project.
     */
    readonly name: string;
    /**
     * (Computed) The unique identifier of the organization with which the project is associated.
     */
    readonly organizationId: string;
    /**
     * (Computed) A list of projects. Each project has the following attributes:
     */
    readonly projects: outputs.GetAccountProjectsProject[];
    /**
     * (Computed) The date and time when the project was updated.
     */
    readonly updatedAt: string;
}
/**
 * The `scaleway.getAccountProjects` data source is used to list all Scaleway projects in an Organization.
 *
 * Refer to the Organizations and Projects [documentation](https://www.scaleway.com/en/docs/organizations-and-projects/) and [API documentation](https://www.scaleway.com/en/developers/api/account/project-api/) for more information.
 *
 * ## Retrieve a Scaleway Projects
 *
 * The following commands allow you to:
 *
 * - retrieve all Projects in an Organization
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@ediri/scaleway";
 *
 * const all = scaleway.getAccountProjects({
 *     organizationId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
 * });
 * ```
 *
 * ## Example Usage
 *
 * ### Deploy an SSH key in all your organization's projects
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@ediri/scaleway";
 *
 * const all = scaleway.getAccountProjects({});
 * const main: scaleway.AccountSshKey[] = [];
 * all.then(all => all.projects).length.apply(rangeBody => {
 *     for (const range = {value: 0}; range.value < rangeBody; range.value++) {
 *         main.push(new scaleway.AccountSshKey(`main-${range.value}`, {
 *             publicKey: local.public_key,
 *             projectId: all.then(all => all.projects[range.value].id),
 *         }));
 *     }
 * });
 * ```
 */
export function getAccountProjectsOutput(args?: GetAccountProjectsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAccountProjectsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("scaleway:index/getAccountProjects:getAccountProjects", {
        "organizationId": args.organizationId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAccountProjects.
 */
export interface GetAccountProjectsOutputArgs {
    /**
     * The unique identifier of the Organization with which the Projects are associated.
     * If no default `organizationId` is set, one must be set explicitly in this datasource
     */
    organizationId?: pulumi.Input<string>;
}
